function Mexport(){
	let acv = [];
	for(let i = 0;i < 16;i++){
		if(document.getElementById("p" + i).checked){
			acv.push(i);
		}
	}
	pt_adj = Number(document.getElementById("pitch").value);
	sf_adj = Number(document.getElementById("scale").value);
	all_tone = Number(document.getElementById("ins").value) + 1;
	all_tone = (all_tone == 0) ? -1 : all_tone;
	Read();
	if(acv.length == 0){
		acv = null;
	}
	Export(acv);
}
var scale = [
	[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
	[ 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1 ],
	[ 0, 0, 0, 0, 0, 0, 0, -1, 0, 0, 0, 1 ],
	[ 0, 0, 0, 0, -1, 0, 0, 2, 0, -1, 0, 1 ],
	[ 0, 0, 2, 0, 0, 0, 0, 0, 0, 2, 0, 0 ],
	[ 0, 0, 2, 0, -1, 0, 0, 0, 0, 2, 0, -1 ],
	[ 0, 0, -1, 0, 2, 0, 0, -1, 0, 1, 0, -1 ],
	[ 0, 0, 0, 0, -1, 1, 0, 0, 0, -1, 0, 0 ],
	[ 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0 ],
	[ 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, -1 ],
	[ 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 0, -1 ],
	[ 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 0, 0 ],
	[ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0 ],
	[ 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 1 ],
	[ 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0 ],
	[ 0, 0, 0, 0, -1, 0, 0, 0, 0, 0, 0, -1 ],
	[ 0, 0, -1, 0, -1, 0, 0, 0, 0, -1, 0, -1 ],
	[ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0 ],
	[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1 ],
	[ 0, 0, -1, 0, -1, 0, 0, -1, 0, -1, 0, -1 ],
	[ 0, 0, -1, 0, -1, 0, 0, -1, 0, 0, 0, -1 ],
	[ 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 0, 0 ],
	[ 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0, -1 ],
	[ 0, 0, -1, 0, 0, 0, 0, 0, 0, -1, 0, -1 ],
	[ 0, 0, 0, 0, -1, 1, 0, 0, 0, 0, 0, 0 ],
	[ 0, 0, -1, 0, -1, -1, 0, -1, 0, -1, 0, -2 ],
	[ 0, 0, -1, 0, -1, 0, 0, 0, 0, 0, 0, -1 ],
	[ 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0 ],
	[ 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, -1 ],
	[ 0, 0, 0, 0, -1, 0, 0, -1, 0, -1, 0, -1 ],
	[ 0, 0, -1, 0, -1, -1, 0, -1, 0, -1, 0, -1 ],
	[ 0, 0, 0, 0, -1, -1, 0, 0, 0, 0, 0, 0 ],
	[ 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, -1 ],
	[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
	[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
	[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
	[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
	[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
	[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
	[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ],
];
function change_s(i){
	conf_tones = scale[i];
	document.getElementById("sc").innerText = document.getElementById("scb").getElementsByTagName("button")[i].innerText;
}
var ins_name =[
"指定なし",
"Acoustic Grand Piano	アコースティック・グランド・ピアノ",
"Bright Acoustic Piano	ブライト・アコースティック・ピアノ",
"Electric Grand Piano	エレクトリック・グランド・ピアノ",
"Honky-tonk Piano	ホンキー・トンク・ピアノ",
"Electric Piano 1	エレクトリック・ピアノ1",
"Electric Piano 2	エレクトリック・ピアノ2",
"Harpsichord	ハープシコード",
"Clavi	クラビ",
"Celesta	チェレスタ",
"Glockenspiel	グロッケン",
"Music box	ミュージック・ボックス（オルゴール）",
"Vibraphone	ビブラフォン",
"Marimba	マリンバ",
"Xylophone	シロフォン",
"Tubular Bells	チューブラ・ベル",
"Dulcimer	ダルシマー",
"Drawbar Organ	ドローバー・オルガン",
"Percussive Organ	パーカッシブ・オルガン",
"Rock Organ	ロック・オルガン",
"Church organ	チャーチ・オルガン",
"Reed organ	リード・オルガン",
"Accordion	アコーディオン",
"Harmonica	ハーモニカ",
"Tango Accordion	タンゴ・アコーディオン",
"Acoustic Guitar (nylon)	アコースティック・ギター（ナイロン）",
"Acoustic Guitar (steel)	アコースティック・ギター（スティール）",
"Electric Guitar (jazz)	エレクトリック・ギター（ジャズ）",
"Electric Guitar (clean)	エレクトリック・ギター（クリーン）",
"Electric Guitar (muted)	エレクトリック・ギター（ミュート）",
"Overdriven Guitar	オーバードライブ・ギター",
"Distortion Guitar	ディストーション・ギター",
"Guitar harmonics	ギター・ハーモニクス",
"Acoustic Bass	アコースティック・ベース",
"Electric Bass (finger)	エレクトリック・ベース（フィンガー）",
"Electric Bass (pick)	エレクトリック・ベース（ピック）",
"Fretless Bass	フレットレス・ベース",
"Slap Bass 1	スラップ・ベース1",
"Slap Bass 2	スラップ・ベース2",
"Synth Bass 1	シンセ・ベース1",
"Synth Bass 2	シンセ・ベース2",
"Violin	バイオリン",
"Viola	ビオラ",
"Cello	チェロ",
"Contrabass	コントラバス",
"Tremolo Strings	トレモロ・ストリングス",
"Pizzicato Strings	ピチカート・ストリングス",
"Orchestral Harp	オーケストラ・ハープ",
"Timpani	ティンパニー",
"String Ensembles 1	ストリング・アンサンブル1",
"String Ensembles 2	ストリング・アンサンブル2",
"SynthStrings 1	シンセ・ストリングス1",
"SynthStrings 2	シンセ・ストリングス2",
"Choir Aahs	ボイス（アー）",
"Voice Oohs	ボイス（ウー）",
"Synth Voice	シンセ・ボイス",
"Orchestra Hit	オーケストラ・ヒット",
"Trumpet	トランペット",
"Trombone	トロンボーン",
"Tuba	チューバ",
"Muted Trumpet	ミュート・トランペット",
"French Horn	フレンチ・ホルン",
"Brass Section	ブラス・セクション",
"Synth Brass 1	シンセ・ブラス1",
"Synth Brass 2	シンセ・ブラス2",
"Soprano Sax	ソプラノ・サックス",
"Alto Sax	アルト・サックス",
"Tenor Sax	テナー・サックス",
"Baritone Sax	バリトン・サックス",
"Oboe	オーボエ",
"English Horn	イングリッシュ・ホルン",
"Bassoon	バスーン",
"Clarinet	クラリネット",
"Piccolo	ピッコロ",
"Flute	フルート",
"Recorder	リコーダー",
"Pan Flute	パン・フルート",
"Blown Bottle	ボトル・ブロウ",
"Shakuhachi	尺八",
"Whistle	ホイッスル（口笛）",
"Ocarina	オカリナ",
"Lead 1 (square)	リード1（矩形波）",
"Lead 2 (sawtooth)	リード2（鋸歯状波）",
"Lead 3 (calliope)	リード3（calliope 蒸気オルガン）",
"Lead 4 (chiff)	リード4（chiff）",
"Lead 5 (charang)	リード5（charang）",
"Lead 6 (voice)	リード6（ボイス）",
"Lead 7 (fifths)	リード7（5度）",
"Lead 8 (bass + lead)	リード8（ベース＋リード）",
"Pad 1 ((new age)	パッド1（ニュー・エイジ）",
"Pad 2 (warm)	パッド2（ウォーム）",
"Pad 3 (polysynth)	パッド3（ポリシンセ）",
"Pad 4 (choir)	パッド4（クワイア）",
"Pad 5 (bowed)	パッド5（bowed）",
"Pad 6 (metallic)	パッド6（メタリック）",
"Pad 7 (halo)	パッド7（halo）",
"Pad 8 (sweep)	パッド8（スウィープ）",
"FX 1 (rain)	FX1（雨）",
"FX 2 (soundtrack)	FX2（サウンドトラック）",
"FX 3 (crystal)	FX3（クリスタル）",
"FX 4 (atmosphere)	FX4（アトモスフィア）",
"FX 5 (brightness)	FX5（ブライトネス）",
"FX 6 (goblins)	FX6（ゴブリン）",
"FX 7 (echoes)	FX7（エコー）",
"FX 8 (sci-fi)	FX8（SF）",
"Sitar	シタール",
"Banjo	バンジョー",
"Shamisen	三味線",
"Koto	琴",
"Kalimba	カリンバ",
"Bag pipe	バグ・パイプ",
"Fiddle	フィドル",
"Shanai	シャナイ",
"Tinkle Bell	ティンカ・ベル",
"Agogo	アゴゴ",
"Steel Drums	スティール・ドラム",
"Woodblock	ウッド・ブロック",
"Taiko Drum	太鼓",
"Melodic Tom	メロディック・タム",
"Synth Drum	シンセ・ドラム",
"Reverse Cymbal	リバース・シンバル",
"Guitar Fret Noise	ギター・フレット・ノイズ",
"Breath Noise	ブレス・ノイズ",
"Seashore	海辺",
"Bird Tweet	鳥のさえずり",
"Telephone Ring	電話のベル",
"Helicopter	ヘリコプター",
"Applause	拍手喝采",
"Gunshot	ガン・ショット",
];